### PR TITLE
how-to for statistics

### PR DESCRIPTION
**Pull request by jvdp1**
@awvwgk I started a tutorial for the functions in stdlib_stats. Comments are welcome ;)

A few questions:
* I tried to compile the examples with fpm, but it didn't succeed because the fpm.toml is not appropriate. Is it on purpose?
* Under `Tutorial`, would it be possible to have a single tab `Statistics` that would include the pages `Descriptive statistics`, `Correlation and variances`,...?

### CODE REVIEW

**Comment by awvwgk** [comment]
Thanks. I think in the current shape those are more suitable for the how to section.

> I tried to compile the examples with fpm, but it didn't succeed because the fpm.toml is not appropriate. Is it on purpose?

Having a `src` directory, even if it is empty, makes it work. This is a bug in fpm, we should report it.

> Under `Tutorial`, would it be possible to have a single tab `Statistics` that would include the pages `Descriptive statistics`, `Correlation and variances`,...?

You can create a new toctree, just like the tutorials/how-tos (`pages/*/index.md`) are nested in the main toctree (`pages/index.md`), we can have a separate section for statistics which contains further entries. Probably easier to show than to explain.

**Comment by jvdp1** [comment]
I moved the pages to the how-to section, and created a new toctree (at least I hope so).
Let me know if it is ok like this. If so, I will then continue the other pages

**Comment by awvwgk** [comment]
Looks good to me.

image

**Comment by jvdp1** [comment]
I completed pages for descriptive statistics, correlations and covariances.
These provide a short introduction to the different functions, but not a complete explanation of the API (that should be the section `reference`).

**Comment by awvwgk** [comment]
@jvdp1 Is this still work in progress or ready to go?

**Comment by jvdp1** [comment]
> @jvdp1 Is this still work in progress or ready to go?

Sorry. I forgot to update the title. Ready to go from my side.

**Pull request merged**
